WIP
pulp/pulp_ansible pull request #1693
Opened 2023-12-05 18:09 UTC by mdellweg

2023-12-11 16:14 UTC, gerrod3 requested changes
How close are we now to fully removing pulp_smash?

2023-12-11 16:14 UTC, gerrod3 commented on pulp_ansible/tests/functional/api/collection/test_signatures.py
> +    print(content_response)
```suggestion
```

2023-12-11 16:14 UTC, gerrod3 commented on pulp_ansible/tests/functional/api/collection/test_signatures.py
> +    print(content_response)
```suggestion
```

2023-12-11 16:56 UTC, mdellweg commented on setup.py
> -            "dynaconf",
If, so this is bad design to have them defined in two places.

2023-12-11 17:44 UTC, mdellweg commented
> How close are we now to fully removing pulp_smash?

There are still some tests to convert. Removing the v2 api & tests will be a big milestone. My impression is the last tests are also not the easiest...

2023-12-11 17:44 UTC, mdellweg commented on setup.py
> -            "dynaconf",
cc @pulp/galaxy

2023-12-13 21:54 UTC, gerrod3 approved these changes

2023-12-13 21:54 UTC, merged