Raises the galaxy-importer version requirement
pulp/pulp_ansible pull request #673
Opened 2021-11-02 20:47 UTC by dkliban

re: #9346

2021-11-02 21:18 UTC, fao89 approved these changes

2021-11-02 21:18 UTC, fao89 commented on requirements.txt
> +galaxy_importer>=0.4.1
👍🏽

2021-11-03 09:38 UTC, mdellweg requested changes
Can you please also remove installing of galaxy-importer from the before-install script? I believe we want to treat that as an external dependency, and so we should only test against released versions. I think, this is what broke the oci nightly image for several days.

2021-11-09 15:35 UTC, mdellweg approved these changes
I see we are installing it via the plugin-template now, which will install from pypi in a release workflow. That will prevent broken releases of this type at least.

2021-11-12 19:16 UTC, fao89 commented
merging to see if it fixes pulp_installer CI:
https://github.com/pulp/pulp_installer/actions/runs/1451438364

2021-11-12 19:17 UTC, merged